#ifndef CPP2_S21_CONTAINERS_S21_CONTAINERSPLUS_ARRAY_S21_ARRAY_H_
#define CPP2_S21_CONTAINERS_S21_CONTAINERSPLUS_ARRAY_S21_ARRAY_H_

namespace s21 {
template <class T>
class array {
 public:
  array();
};
}  // namespace s21

#endif  // CPP2_S21_CONTAINERS_S21_CONTAINERSPLUS_ARRAY_S21_ARRAY_H_
